name: "default"
description: "Default neutral professional style"

colors:
  primary: "#2C3E50"      # Dark blue-gray
  accent: "#3498DB"       # Medium blue
  light: "#ECF0F1"        # Light gray background
  text: "#333333"         # Dark gray text
  muted: "#7F8C8D"        # Muted gray
  success: "#27AE60"      # Green for included items
  warning: "#E67E22"      # Orange for exclusions

typography:
  font_family: "Arial"
  heading1_size: 28
  heading2_size: 24
  heading3_size: 20
  body_size: 22
  small_size: 18

spacing:
  section_before: 400     # Twips before section headers
  section_after: 200      # Twips after section headers
  paragraph_after: 120    # Twips after paragraphs

contact:
  company: ""
  tagline: ""
  email: ""
